config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  

   root 'pages#index'

resources :articles do
  collection do
    get :archived
  end
  collection do
    get :category
  end
end

resources :netcams
match 'articles/by_year_and_month/:year/:month' => 'artilces#by_year_and_month', :via => [:get], :as => 'articles_by_year_and_month'
match 'articles/by_tag/:tag' => 'artilces#by_tag', :via => [:get], :as => 'articles_by_tag'

resources :pages
get 'faq' => 'pages#faq'
get 'services' => 'pages#services'
get 'contact' => 'pages#contact'
get 'search-results' => 'pages#search-results'
get 'admin' => 'articles#admin'
get '404' => 'pages#404'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  

  def tag_list
  self.tags.collect do |tag|
    tag.name
  end.join(", ")
  end

  def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # http://tutorials.jumpstartlab.com/projects/articlesger.html#i3:-tagging
    before_action :authenticate_user!, :except => [:show, :index, :archived, :category]
    def index
        @articles = Article.order("date DESC").all #Article.where('extract(year from date) = ?', 2015)
        # @articles = Article.order("date DESC").all.paginate(page: params[:page], :per_page => 5)
        @tags = Tag.all
        @articles_by_month = Article.order("date DESC").all.group_by { |article| article.date.strftime("%B %Y") }
        @latests = Article.order("date DESC").limit(3)
    end
       
    def archived
      @articles =  Article.order("date DESC").where(['extract(year from date) = ?', params[:month].split(' ').last]).where(['extract(month from date) = ?', Date::MONTHNAMES.index(params[:month].split(' ').first)])
      @tags = Tag.all
      @articles_by_month = Article.order("date DESC").all.group_by { |article| article.date.strftime("%B %Y") }
    end
    
    def category
      # http://stackoverflow.com/questions/18908608/rails-display-all-posts-with-current-category-id
      @tag = Tag.find_by_name(params[:tag])
      @articles = @tag.articles.order("date DESC").paginate(page: params[:page], :per_page => 5) 
      @tags = Tag.all
      @articles_by_month = Article.order("date DESC").all.group_by { |article| article.date.strftime("%B %Y") }
    end
    
    # http://commandercoriander.net/blog/2013/09/15/customizing-the-rails-index-action/
    # http://stackoverflow.com/questions/15060479/multiple-where-conditions-in-rails
    # http://stackoverflow.com/questions/15498723/how-do-i-convert-a-month-name-into-a-month-integer-in-ruby
   
      
    def archives_list
      @archive = Archive.order("date DESC").where('extract(year  from date) = ?', params[:year]).where('extract(month  from date) = ?', params[:month]).order("date DESC")
    end  
    def archives
    end
   
    def new
        @article = Article.new
       
    end
    
    def admin
      @articles = Article.all
    end
    
    def edit
      @article= Article.find(params[:id])
     
    end
    
   
    
    
    def create
         @article = Article.new(article_params)
         @article.save
        redirect_to @article
    end
    
    def show
        # @article = Article.find(params[:id])
        @article = Article.find(params[:id]) #@article = Article.where('extract(year from date) = ?', params[:id])
        @tags = Tag.all
        @articles_by_month = Article.all.group_by { |article| article.date.strftime("%B %Y") }
        @latests = Article.order("date DESC").limit(3)
    end
    
    def update
      @article = Article.find(params[:id])
      @article.update(article_params)

      redirect_to article_path(@article)
    end
    
    
    private
            def article_params
              params.require(:article).permit(:title, :contentshort, :contentlong, :date, :tag_list)
            end
end

app/controllers/netcams_controller.rb
class NetcamsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def faq
         @latests = Article.order("date DESC").limit(3)
    end
    def contact
    end
    def index
        @latests = Article.order("date DESC").limit(3)
        require 'uri'
        #  url = URI.encode(request.referer.to_s)
        # # # url=request.referer
        #  uri = URI.parse(url)
        #  @uri=uri.host.split('/').last
        # @uri = if URI(request.referer).path =="/" 
        uri= URI(request.referrer.to_s)
        @uri=uri.host
    end
    
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  @tag = Tag.find(params[:id])
  end
  
  def index
        @tags = Tag.all
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # http://stackoverflow.com/questions/3705898/best-way-to-add-current-class-to-nav-in-rails-3
   def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'active' : ''

  content_tag(:li, :class => class_name) do
    link_to link_text, link_path
  end
end

      
     
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/netcams_helper.rb
module NetcamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_archive.html.erb
<h6 class="text-uppercase text-spacing-60">Archives</h6>
                    <div class="text-subline"></div>

<ul class="list list-marked offset-top-30">
<% @articles_by_month.each do |monthname, articles| %>
  <li><%= link_to monthname, archived_articles_path(:month => monthname) %> (<%= articles.count %>) </li>
  
  <!--<ul id="archive">-->
  <!-- <%# articles.each do |article| %>-->
  <!--<li class="archive-post"><%#= link_to article.title, article_path(article) %></li>-->
<!--<%# end %>-->
<% end %>



                      <!--<li><a href="#">January 2016 <span class="text-dark">(17)</span></a></li>-->
                      <!--<li><a href="#">December 2015 <span class="text-dark">(121)</span></a></li>-->
                      <!--<li><a href="#">November 2015 <span class="text-dark">(19)</span></a></li>-->
                      <!--<li><a href="#">October 2015 <span class="text-dark">(9)</span></a></li>-->
                      <!--<li><a href="#">September 2015 <span class="text-dark">(25)</span></a></li>-->
                    </ul>

app/views/articles/_body.html.erb
<% @articles.each do |article| %>
                        <article class="post post-default text-left">
                          <!-- Post Header-->
                          <div class="header post-header">
                            <!-- Post Meta-->
                            <ul class="post-controls list-inline list-inline-sm p text-dark">
                              <li><span class="text-middle icon-xxs text-picton-blue mdi mdi-clock"></span>
                                <time datetime="01-01-2016" class="text-middle small"><%= article.date.strftime('%b %e, %Y') %></time>
                              </li>
                              <li><span class="text-middle icon-xxs text-picton-blue mdi mdi-account-outline">&nbsp;</span><span class="text-middle small">PaulC</span></li>
                              <li><span class="text-middle icon-xxs text-picton-blue mdi mdi-folder-outline">&nbsp;</span>
                              
                              <% article.tags.each do |tag| %>
                                <%= link_to tag.name.titlecase, category_articles_path(tag), class: 'text-middle' %>
                                <% end %>
                                <% article.tags.map{ |tag| link_to(tag.name, category_articles_path(tag))}.join(", ").html_safe  %>
                              </li>
                              <!--<li><span class="text-middle icon-xxs text-picton-blue mdi mdi-comment-multiple-outline">&nbsp;</span><a href="articles-default-single-left-sidebar.html#comments" class="text-middle small">42<span>&nbsp;Comments</span></a></li>-->
                            </ul>
                              <!-- Post Meta-->
                              <h3 class="post-title"><%= link_to  article.title.html_safe, article_path(article) %></h3>
                                <!-- Post Media-->
                                <!--<div class="post-media offset-top-34">-->
                                <!--  <header class="post-media">-->
                                <!--    <div data-photo-swipe="gallery" class="thumbnail-classic" >-->
                                      <!--<a class="thumbnail-classic" href="articles-default-single-left-sidebar.html" target="_self">-->
                                <!--                        <figure><img width="570" height="321" src="assets/articles/WirelessCamera3.png" alt="">-->
                                <!--                        </figure>-->
                                      <!--</a>-->
                                <!--    </div>-->
                                <!--  </header>-->
                                <!--</div>-->
                          </div>
                            <!-- PostContent-->
                          <section class="post-content offset-top-41">
                            <%= article.contentshort.html_safe %> 
                            
                            <% unless article.contentlong.blank? %> (cont.)
                            <br>
                             <%= link_to 'Read More', article_path(article), class: "offset-top-10 btn btn-default" %>
                            <% end %>
                          </section>
                        </article>
                      <hr class="hr offset-top-66">
                        
                    <% end %>
                  
                  <div class="offset-top-66">
                                    <!-- Bootstrap Pagination-->
                                    <!--<%#= will_paginate %>-->
                                    
                  </div>

app/views/articles/admin.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/edit.html.erb
<h1>Editing articles</h1>
 
<%= render partial: 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/new.html.erb
<h1>New articles Entry</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<div class="page text-center">
      <!-- Page Header-->
     
     
      <header class="page-head slider-menu-position">
          <%= render 'layouts/navbar' %>
      </header>

      <!-- Page Content-->
      <main class="page-content section-98 section-sm-110">
        <div class="shell">
          <div class="range range-xs-center">
            <div class="cell-md-8 cell-md-push-2">
              <div class="inset-md-left-20">
                
                <section>
                  
                                  <!-- Post Wide-->
                                  <article class="post post-default text-left">
                                   
                                    <!-- Post Header-->
                                    <div class="header post-header">
                                      <!-- Post Meta-->
                                      <ul class="post-controls list-inline list-inline-sm p text-dark">
                                        <li><span class="text-middle icon-xxs text-picton-blue mdi mdi-clock"></span>
                                          <time datetime="2016-01-01" class="text-middle small"><%= @article.date.strftime("%b %-d, %Y") %></time>
                                        </li>
                                        <li><span class="text-middle icon-xxs text-picton-blue mdi mdi-account-outline">&nbsp;</span><span class="text-middle small">PaulC</span></li>
                                        <li><span class="text-middle icon-xxs text-picton-blue mdi mdi-folder-outline">&nbsp;</span>
                                         
                                          
                                          <% @article.tags.each do |tag| %>
                                            <%= link_to tag.name.titlecase, category_articles_path(tag), class: 'text-middle' %>
                                          <% end %>
                                
                                          
                                        
                                        
                                        
                                        <!--<a href="#" class="text-middle">UX</a>, <a href="#" class="text-middle">Design</a>-->
                                        </li>
                                        <!--<li><span class="text-middle icon-xxs text-picton-blue mdi mdi-comment-multiple-outline">&nbsp;</span><a href="#comments" class="text-middle small">4<span>&nbsp;Comments</span></a></li>-->
                                      </ul>
                                      <!-- Post Meta-->
                                      <h3 class="post-title"><%= @article.title %></h3>
                                    
                                      <!-- Post Media-->
                                      <!--<div class="post-media offset-top-34">-->
                                      <!--  <header class="post-media">-->
                                      <!--    <div data-photo-swipe="gallery"><a class="thumbnail-classic" href="#" target="_self">-->
                                      <!--                        <figure><img width="570" height="321" src="images/article/post-01-570x321.jpg" alt="">-->
                                      <!--                        </figure></a>-->
                                      <!--    </div>-->
                                      <!--  </header>-->
                                      <!--</div>-->
                                    </div>
                                    <!-- PostContent-->
                                    <section class="post-content offset-top-41">
                                      <%= @article.contentshort.html_safe %>
                                      <%= @article.contentlong.html_safe %>
                                    </section>
                                    
                                  </article>
                  <!--<footer class="offset-top-50 text-sm-left clearfix">-->
                  <!--  <h6 class="pull-sm-left">Share this post:</h6>-->
                  <!--  <ul class="list-inline small pull-sm-right p offset-top-0 text-sm-right">-->
                  <!--    <li><a href="#" class="fa fa-facebook"></a></li>-->
                  <!--    <li><a href="#" class="fa fa-twitter"></a></li>-->
                  <!--    <li><a href="#" class="fa fa-google-plus"></a></li>-->
                  <!--    <li><a href="#" class="fa fa-pinterest"></a></li>-->
                  <!--  </ul>-->
                  <!--</footer>-->
                  <hr class="offset-top-66">
                  <!--<h4 class="offset-top-66 text-uppercase text-spacing-120 text-left text-bold">Related Posts</h4>-->
                  <!--<div class="range offset-top-41">-->
                  <!--  <div class="cell-md-6">-->
                                      <!-- Post Widget-->
                  <!--                    <article class="post widget-post text-left"><a href="article-classic-single-post.html">-->
                  <!--                        <div class="unit unit-horizontal unit-spacing-xs unit-middle">-->
                  <!--                          <div class="unit-left"><img width="60" height="60" src="images/users/user-john-doe-60x60.jpg" alt="" class="img-circle"></div>-->
                  <!--                          <div class="unit-body">-->
                  <!--                            <div class="post-meta"><span class="icon-xxs mdi mdi-arrow-right text-picton-blue"></span>-->
                  <!--                              <time datetime="2016-01-01" class="text-dark">05/14/2015</time>-->
                  <!--                            </div>-->
                  <!--                            <div class="post-title">-->
                  <!--                              <h6 class="text-regular">Making Money Online with Your Computer Only</h6>-->
                  <!--                            </div>-->
                  <!--                          </div>-->
                  <!--                        </div></a></article>-->
                  <!--    <div class="offset-top-24">-->
                                        <!-- Post Widget-->
                  <!--                      <article class="post widget-post text-left"><a href="article-classic-single-post.html">-->
                  <!--                          <div class="unit unit-horizontal unit-spacing-xs unit-middle">-->
                  <!--                            <div class="unit-left"><img width="60" height="60" src="images/users/user-bernard-show-60x60.jpg" alt="" class="img-circle"></div>-->
                  <!--                            <div class="unit-body">-->
                  <!--                              <div class="post-meta"><span class="icon-xxs mdi mdi-arrow-right text-picton-blue"></span>-->
                  <!--                                <time datetime="2016-01-01" class="text-dark">05/18/2015</time>-->
                  <!--                              </div>-->
                  <!--                              <div class="post-title">-->
                  <!--                                <h6 class="text-regular">Proper Color Solutions For The Office</h6>-->
                  <!--                              </div>-->
                  <!--                            </div>-->
                  <!--                          </div></a></article>-->
                  <!--    </div>-->
                  <!--  </div>-->
                  <!--  <div class="cell-sm-6 offset-top-24 offset-sm-top-0">-->
                                      <!-- Post Widget-->
                  <!--                    <article class="post widget-post text-left"><a href="article-classic-single-post.html">-->
                  <!--                        <div class="unit unit-horizontal unit-spacing-xs unit-middle">-->
                  <!--                          <div class="unit-left"><img width="60" height="60" src="images/users/user-sam-cole-60x60.jpg" alt="" class="img-circle"></div>-->
                  <!--                          <div class="unit-body">-->
                  <!--                            <div class="post-meta"><span class="icon-xxs mdi mdi-arrow-right text-picton-blue"></span>-->
                  <!--                              <time datetime="2016-01-01" class="text-dark">05/9/2015</time>-->
                  <!--                            </div>-->
                  <!--                            <div class="post-title">-->
                  <!--                              <h6 class="text-regular">Going Green Is So Much Simpler Than Most People Think</h6>-->
                  <!--                            </div>-->
                  <!--                          </div>-->
                  <!--                        </div></a></article>-->
                  <!--    <div class="offset-top-24">-->
                                        <!-- Post Widget-->
                  <!--                      <article class="post widget-post text-left"><a href="article-classic-single-post.html">-->
                  <!--                          <div class="unit unit-horizontal unit-spacing-xs unit-middle">-->
                  <!--                            <div class="unit-left"><img width="60" height="60" src="images/users/user-july-mao-60x60.jpg" alt="" class="img-circle"></div>-->
                  <!--                            <div class="unit-body">-->
                  <!--                              <div class="post-meta"><span class="icon-xxs mdi mdi-arrow-right text-picton-blue"></span>-->
                  <!--                                <time datetime="2016-01-01" class="text-dark">05/21/2015</time>-->
                  <!--                              </div>-->
                  <!--                              <div class="post-title">-->
                  <!--                                <h6 class="text-regular">Let’s Change the world</h6>-->
                  <!--                              </div>-->
                  <!--                            </div>-->
                  <!--                          </div></a></article>-->
                  <!--    </div>-->
                  <!--  </div>-->
                  <!--</div>-->
                  
                </section>
              </div>
            </div>
            <div class="cell-md-4 cell-md-push-1 offset-top-66 offset-md-top-0">
              <!-- Section article Modern-->
              <aside class="text-left">
                
                <%= render :partial => 'tags/tags' %>
                
                <%= render :partial => 'archive' %>
              </aside>
            </div>
          </div>
        </div>
      </main>
      <!-- Page Footers-->
      <!-- Default footer-->
       <%= render 'layouts/footer' %>
    </div>
    

app/views/layouts/_footer.html.erb
<footer class="section-relative section-top-66 section-bottom-34 page-footer bg-gray-base context-dark">
        <div class="shell">
          <div class="range range-sm-center text-lg-left">
            <div class="cell-sm-8 cell-md-12">
              <div class="range range-xs-center">
                <div class="cell-xs-7 text-xs-left cell-md-4 cell-lg-3 cell-lg-push-4">
                  <h6 class="text-uppercase text-spacing-60">Latest articles</h6>
                   <%= render partial: 'articles/latest' %>
                        
                </div>
                <div class="cell-xs-5 offset-top-41 offset-xs-top-0 text-xs-left cell-md-3 cell-lg-2 cell-lg-push-3">
                  <!--<h6 class="text-uppercase text-spacing-60">Useful Links</h6>-->
                  <!--<div class="reveal-block">-->
                  <!--  <div class="reveal-inline-block">-->
                  <!--    <ul class="list list-marked">-->
                  <!--      <li><a href="about-us.html">About Us</a></li>-->
                  <!--      <li><a href="contact-us.html">Contact Us</a></li>-->
                  <!--      <li><a href="services.html">Services</a></li>-->
                  <!--      <li><%= link_to "services", services_path %></li>-->
                  <!--      <li><a href="clients.html">Clients</a></li>-->
                  <!--    </ul>-->
                  <!--  </div>-->
                  <!--</div>-->
                </div>
                <div class="cell-xs-12 offset-top-41 cell-md-5 offset-md-top-0 text-md-left cell-lg-4 cell-lg-push-2">
                  <h6 class="text-uppercase text-spacing-60">Newsletter</h6>
                  <p>Keep up with our always upcoming  product features  and technologies. Enter your e-mail and subscribe to  our newsletter.</p>
                  <div class="offset-top-30">
                          <form data-form-output="form-subscribe-footer" data-form-type="subscribe" method="post" action="bat/rd-mailform.php" class="rd-mailform">
                            <div class="form-group">
                              <div class="input-group input-group-sm"><span class="input-group-addon"><span class="input-group-icon mdi mdi-email"></span></span>
                                <input placeholder="Coming Soon" type="email" name="email" data-constraints="@Required @Email" class="form-control"><span class="input-group-btn">
                                  <button type="submit" class="btn btn-sm btn-primary">Subscribe</button></span>
                              </div>
                            </div>
                            <div id="form-subscribe-footer" class="form-output"></div>
                          </form>
                  </div>
                </div>
                <div class="cell-xs-12 offset-top-66 cell-lg-3 cell-lg-push-1 offset-lg-top-0">
                  <!-- Footer brand-->
                  <div class="footer-brand"><%= link_to image_tag("dsc/logo-light-dsc.png", :alt => "", :style => 'margin-top: -5px;margin-left: -15px; width=138 height=41'), root_path %></div>
                  <p class=" offset-top-4">Denver Security Camera</p>
                  <p class=" offset-top-4"><i>See what you've been missing</i></p>
                  <p class=" offset-top-4">Call Today! 303-301-5124</p>
                        <!--<ul class="list-inline">-->
                        <!--  <li><a href="#" class="icon fa fa-facebook icon-xxs icon-circle icon-darkest-filled"></a></li>-->
                        <!--  <li><a href="#" class="icon fa fa-twitter icon-xxs icon-circle icon-darkest-filled"></a></li>-->
                        <!--  <li><a href="#" class="icon fa fa-google-plus icon-xxs icon-circle icon-darkest-filled"></a></li>-->
                        <!--  <li><a href="#" class="icon fa fa-linkedin icon-xxs icon-circle icon-darkest-filled"></a></li>-->
                        <!--</ul>-->
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="shell offset-top-50">
          <p class="small text-darker">Denver Security Camera &copy; <span id="copyright-year"></span>
          <!--. <a href="privacy.html">Privacy Policy</a>-->
            <!-- {%FOOTER_LINK}-->
          </p>
        </div>
      </footer>

app/views/layouts/_navbar.html.erb
<div class="rd-navbar-wrap">
          <nav data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" class="rd-navbar rd-navbar-default rd-navbar-transparent" data-lg-auto-height="true" data-md-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-stick-up="true">
            <div class="rd-navbar-inner">
              
              <!-- RD Navbar Panel-->
              <div class="rd-navbar-panel">
                <!-- RD Navbar Toggle-->
                <button data-rd-navbar-toggle=".rd-navbar, .rd-navbar-nav-wrap" class="rd-navbar-toggle"><span></span></button>
                <!--Navbar Brand-->
                <div class="logo"><%= link_to image_tag("dsc/logo-light-dsc.png", :alt => "", :style => 'margin-top: -5px;margin-left: -15px; width=138 height=41'), root_path %>
                <!--<span class="p text-bold text-lighter" style="padding-left:40px; white-space:nowrap; font-size:150%">303-301-5124</span></div>-->
                </div>
                 <div class ="company">Denver Security Camera</div>
                <div class ="phone">303-301-5124</div>
               
             
              <div class="rd-navbar-menu-wrap">
                
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-mobile-scroll">
                    <!--Navbar Brand Mobile-->
                    <div class="rd-navbar-mobile-brand"><%= link_to image_tag("dsc/logo-light-dsc.png", :alt => "", :style => 'margin-top: -5px;margin-left: -15px; width=138 height=41'), root_path %></div>
                    <!--<div class="form-search-wrap">-->
                      <!-- RD Search Form-->
                    <!--  <form action="search-results" method="GET" class="form-search rd-search">-->
                    <!--    <div class="form-group">-->
                    <!--      <label for="rd-navbar-form-search-widget" class="form-label form-search-label form-label-sm">Search</label>-->
                    <!--      <input id="rd-navbar-form-search-widget" type="text" name="s" autocomplete="off" class="form-search-input input-sm form-control form-control-gray-lightest input-sm"/>-->
                    <!--    </div>-->
                    <!--    <button type="submit" class="form-search-submit"><span class="mdi mdi-magnify"></span></button>-->
                    <!--  </form>-->
                    <!--</div>-->
                    <!-- RD Navbar Nav-->
                    <ul class="rd-navbar-nav">
                      <li class="<%= "active" if current_page?(root_path) %>"><%= link_to "home", root_path %></li>
                      
                      <% if current_page?(root_path) %>
                        <li><%= link_to "Solutions", "#solutions" %></li>
                        <% else %>
                        <li><%= link_to "Solutions", root_url(:anchor => "solutions") %></li>
                      <% end %>
      
      
                      
                      <li class="<%= "active" if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
                      <li class="<%= "active" if current_page?(faq_path) %>"><%= link_to "faq", faq_path %></li>
                      
                       <li class="<%= "active" if controller.controller_name == 'articles' %>"><%= link_to '/articles' do %><span>articles</span><span class="rd-navbar-label text-middle label-custom label-danger label-xs-custom label-rounded-custom label">new</span>
                      <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
                <!--RD Navbar Search-->
                <!--<div class="rd-navbar-search"><a data-rd-navbar-toggle=".rd-navbar-inner,.rd-navbar-search" href="#" class="rd-navbar-search-toggle mdi"><span></span></a>-->
                <!--  <form action="search-results" method="GET" class="rd-navbar-search-form search-form-icon-right rd-search">-->
                <!--    <div class="form-group">-->
                <!--      <label for="rd-navbar-search-form-input" class="form-label">Type and hit enter...</label>-->
                <!--      <input id="rd-navbar-search-form-input" type="text" name="s" autocomplete="off" class="rd-navbar-search-form-input form-control form-control-gray-lightest"/>-->
                <!--    </div>-->
                    <!--button(type="submit").rd-navbar-search-form-submit.mdi.mdi-magnify-->
                <!--  </form>-->
                  <!--div.rd-navbar-live-search-results-->
                  <!--button(data-rd-navbar-toggle=".rd-navbar-search, .rd-navbar-inner, .rd-navbar-live-search-results").rd-navbar-search-toggle-->
                  <!--  span-->
                <!--</div>-->
                
                
              </div>
            </div>
          </nav>
        </div>